import 'server-only';
import {Redis} from '@upstash/redis';
import {createHash} from 'node:crypto';
import {validateOffer} from '../offers.mjs';
const key=()=>`colorstackuta:offers:${process.env.VERCEL_ENV==='production'?'production':'preview'}:v1`;
function db(){return new Redis({url:process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL,token:process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN});}
export async function offers(){const values=await db().get(key());return Object.values(values||{}).map(v=>typeof v==='string'?JSON.parse(v):v);}
export async function submitOffer(user,body){const data=validateOffer(body);const id=createHash('sha256').update(JSON.stringify([user.id,data.company.toLowerCase(),data.role.toLowerCase(),data.type,data.date])).digest('hex');const row={...data,id,userId:user.id,name:[user.firstName,user.lastName].filter(Boolean).join(' ')||'Member',status:'pending',addToBaseline:false,submittedAt:new Date().toISOString()};await db().eval("local rows=cjson.decode(redis.call('GET',KEYS[1]) or '{}'); if rows[ARGV[1]] then return 0 end; rows[ARGV[1]]=cjson.decode(ARGV[2]); redis.call('SET',KEYS[1],cjson.encode(rows)); return 1",[key()],[id,JSON.stringify(row)]);return id;}
export async function reviewOffer(user,body){if(!/^[a-f0-9]{64}$/.test(body.id||'')||!['approved','rejected','pending'].includes(body.status)||typeof body.addToBaseline!=='boolean')throw Error('Choose a valid review decision.');const result=await db().eval("local rows=cjson.decode(redis.call('GET',KEYS[1]) or '{}'); local row=rows[ARGV[1]]; if not row then return 0 end; if row.userId==ARGV[2] then return -1 end; row.status=ARGV[3]; row.addToBaseline=ARGV[4]=='true'; row.reviewedBy=ARGV[2]; row.reviewedAt=ARGV[5]; redis.call('SET',KEYS[1],cjson.encode(rows)); return 1",[key()],[body.id,user.id,body.status,String(body.status==='approved'&&body.addToBaseline),new Date().toISOString()]);if(result===0)throw Error('Report not found.');if(result===-1)throw Error('Another officer must review your own offer.');}
