import {identity,officer,sameOrigin} from '@/lib/server/auth';
import {offers,submitOffer,reviewOffer} from '@/lib/server/offers';
import {find,TABLES} from '@/lib/server/profiles';
export const dynamic='force-dynamic';
const reply=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(request){try{const user=await identity();if(!user)return reply({error:'Verified sign-in required.'},401);if(new URL(request.url).searchParams.get('review')==='1'){if(!await officer())return reply({error:'Officer access required.'},403);return reply({reports:await offers()});}return reply({reports:(await offers()).filter(r=>r.userId===user.id)});}catch{return reply({error:'Offer reports are temporarily unavailable.'},503);}}
async function write(request,review){if(!sameOrigin(request))return reply({error:'Request origin rejected.'},403);try{const user=review?await officer():await identity();if(!user)return reply({error:'Access denied.'},403);const raw=await request.text();if(raw.length>2000)return reply({error:'Request too large.'},413);let body;try{body=JSON.parse(raw);}catch{return reply({error:'Invalid request.'},400);}if(!body||typeof body!=='object')return reply({error:'Invalid request.'},400);if(review){await reviewOffer(user,body);}else{if(!await find(TABLES.members,user.id))return reply({error:'Save your member profile first.'},409);const own=(await offers()).filter(r=>r.userId===user.id);if(own.length>=30)return reply({error:'Contact an officer to add more reports.'},429);await submitOffer(user,body);}return reply({ok:true});}catch(e){if(/Complete|Choose|Another officer|Report not found/.test(e.message))return reply({error:e.message},400);console.error('Offer report save failed');return reply({error:'Could not save the report. Please retry.'},503);}}
export const POST=request=>write(request,false);
export const PATCH=request=>write(request,true);
