import AboutFrame from "@/components/AboutFrame";
import { Board, Archives, Traditions, National } from "@/components/AboutSections";
import { MILESTONES, PILLARS, aboutMetadata } from "@/lib/about";
import "./about.css";
export const metadata = aboutMetadata("About ColorStack UTA | Technology Community at UT Arlington", "Learn about ColorStack UTA, a student-led technology community at The University of Texas at Arlington supporting Black and Latinx students through community, technical development, career opportunities, and industry connections.", "/about");
export default function About() { return <AboutFrame current="/about">
<section className="cs-shell cs-section about-hero"><div><p className="cs-eyebrow">OUR STORY / COLORSTACK UTA</p><h1 className="cs-display">Built on community.<br/>Driven by <em>possibility.</em></h1><p className="about-body">ColorStack UTA began in Spring 2024 with a simple idea: Black and Latinx students pursuing technology shouldn’t have to navigate it alone.</p></div><figure><img src="/images/chapter-campus.png" alt="ColorStack UTA students together by the UTA campus landmark"/><figcaption>OUR PEOPLE. OUR CAMPUS. OUR NEXT CHAPTER.</figcaption></figure></section>
<section className="cs-shell about-origin"><p className="cs-eyebrow">STUDENT LED / UT ARLINGTON</p><div><p>We’re a student-led technology organization at The University of Texas at Arlington. What started as a campus community has grown into hundreds of students learning together, building relationships, connecting with industry, and opening doors for one another.</p><p>We’re building a place where finding your people and finding your next opportunity can happen at the same time.</p></div></section>
<section className="cs-shell cs-section"><div className="cs-section-heading"><div><p className="cs-eyebrow">STILL WRITING THE STORY</p><h2>From a beginning.<br/><em>To what’s next.</em></h2></div></div><ol className="about-timeline">{MILESTONES.map(item => <li key={item.year}><span>{item.year}</span><div><h3>{item.title}</h3><p>{item.body}</p>{item.photo && <figure className="about-milestone-photo"><img src={item.photo} alt={item.photoAlt} loading="lazy"/>{item.photoCaption && <figcaption className="about-caption">{item.photoCaption}</figcaption>}</figure>}</div></li>)}</ol></section>
<section className="cs-pathways"><div className="cs-shell cs-section"><div className="cs-section-heading"><div><p className="cs-eyebrow">WHAT WE’RE HERE TO DO</p><h2>People. Practice.<br/><em>Possibility.</em></h2></div></div><div className="about-pillars">{PILLARS.map((item,index) => <article key={item.name}><p className="cs-eyebrow">0{index+1} / {item.name}</p><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></div></section>
<section className="cs-shell cs-section"><div className="cs-section-heading"><div><p className="cs-eyebrow">THE PEOPLE BEHIND THE CHAPTER</p><h2>Built by <em>students.</em></h2></div><p>Every semester, students step forward to help build what’s next.</p></div><Board/><a className="cs-text-link about-more" href="/about/leadership">Meet current leadership →</a></section>
<section className="cs-shell cs-section about-rule"><div className="cs-section-heading"><div><p className="cs-eyebrow">THE PEOPLE WHO BUILT IT</p><h2>Every semester leaves<br/><em>something behind.</em></h2></div><p>Preserving the people and moments that shaped each semester.</p></div><Archives/><a className="cs-text-link about-more" href="/about/archive">Explore the chapter archive →</a></section>
<section className="cs-shell cs-section about-rule"><div className="cs-section-heading"><div><p className="cs-eyebrow">MORE THAN MEETINGS</p><h2>Some things become <em>tradition.</em></h2></div><p>The moments, rituals, and ideas that become part of what it means to be ColorStack UTA.</p></div><Traditions/><a className="cs-text-link about-more" href="/about/traditions">Explore our traditions →</a></section>
<section className="cs-shell cs-section about-rule"><div className="cs-section-heading"><div><p className="cs-eyebrow">PART OF SOMETHING BIGGER</p><h2>From UTA to a<br/><em>national community.</em></h2></div></div><National/></section>
</AboutFrame>; }
