"use client";
import MajorField from './MajorField';
import {useEffect,useRef,useState} from 'react';
import {MONTHS,STANDINGS,INTERESTS,ETHNICITIES,GENDERS,LGBTQ,INTERNATIONAL,EMPTY_PROFILE,CONSENT_TEXT} from '@/lib/profile-fields.mjs';
const inputClass='w-full bg-cream border border-navy/20 rounded-sm px-3 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brass/50';
const buttonClass='inline-flex justify-center items-center bg-navy text-cream px-5 py-3 rounded-sm font-bold uppercase tracking-widest text-xs whitespace-nowrap disabled:opacity-50';
function Field({label,children}){return <label className="block"><span className="block text-sm font-semibold mb-2">{label}</span>{children}</label>;}
export default function MemberProfile(){
 const [form,setForm]=useState({...EMPTY_PROFILE});const [saved,setSaved]=useState(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [dirty,setDirty]=useState(false);const [reload,setReload]=useState(0);const fileInput=useRef(null);
 const year=new Date().getFullYear();
 useEffect(()=>{let active=true;setLoading(true);setError('');fetch('/api/profile',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active){setSaved(d);setForm(d.profile);setDirty(false);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[reload]);
 function change(key,value){setForm(f=>({...f,[key]:value}));setDirty(true);setNotice('');}
 function multi(key,value){let values=form[key];if(value==='Prefer not to say') values=values.includes(value)?[]:[value];else values=values.filter(x=>x!=='Prefer not to say').includes(value)?values.filter(x=>x!==value&&x!=='Prefer not to say'):[...values.filter(x=>x!=='Prefer not to say'),value];change(key,values);}
 async function action(url,options,success){setBusy(true);setError('');setNotice('');try{const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||(r.status===413?'Choose a PDF under 3 MB.':`Request failed (${r.status}). Please try again.`));setSaved(d);setForm(d.profile);setDirty(false);setNotice(success);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(files){const file=files?.[0];if(!file)return;if(dirty){setError('Save your profile changes before uploading a resume.');return;}if(!file.name.toLowerCase().endsWith('.pdf')||file.size>3*1024*1024){setError('Choose a PDF under 3 MB.');return;}const data=new FormData();data.append('resume',file);await action('/api/profile/resume',{method:'POST',body:data},'Resume saved. Review the sharing checkbox below if you want this version included in resume books.');}
 function select(key,label,options,required=false){return <Field label={label}><select required={required} className={inputClass} value={form[key]} onChange={e=>change(key,e.target.value)}><option value="">{required?'Select…':'Skip this question'}</option>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></Field>;}
 if(loading)return <p className="mt-8" role="status">Loading your profile…</p>;
 if(!saved)return <div className="mt-8 border border-navy/20 p-5"><p role="alert">{error||'Unable to load your profile.'}</p><button className={buttonClass+' mt-4'} onClick={()=>setReload(x=>x+1)}>Try again</button></div>;
 return <form className="mt-10 border-t border-navy/15 pt-8" onSubmit={e=>{e.preventDefault();action('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)},'Profile saved. Your information will be here when you sign in again.');}}>
 <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-brass uppercase text-xs tracking-widest font-bold">Your member profile</p><h2 className="font-serif text-3xl mt-2">Make your next move.</h2></div><span className="text-xs text-navy/60 whitespace-nowrap">{dirty?'Unsaved changes':saved.exists?'Saved profile':'New profile'}</span></div>
 <p className="text-sm text-navy/70 mt-4 mb-7">Your verified sign-in email identifies your account. Saving a profile does not mark dues paid. Fields marked * are required.</p>
 <fieldset disabled={busy} className="space-y-8 disabled:opacity-70">
 <section aria-labelledby="academic-title"><h3 id="academic-title" className="font-serif text-xl mb-5">Academic details</h3><div className="grid sm:grid-cols-2 gap-5">
 <Field label="Full name *"><input required autoComplete="name" maxLength={120} className={inputClass} value={form.name} onChange={e=>change('name',e.target.value)}/></Field>
 <MajorField value={form.major} onChange={value=>change('major',value)}/>
 {select('standing','Class year / academic standing *',STANDINGS,true)}{select('graduationMonth','Graduation month *',MONTHS,true)}
 <Field label="Graduation year *"><input required type="number" min={year-10} max={year+12} className={inputClass} value={form.graduationYear} onChange={e=>change('graduationYear',e.target.value)}/></Field>
 </div></section>
 <section className="border-t border-navy/10 pt-7" aria-labelledby="career-title"><h3 id="career-title" className="font-serif text-xl mb-5">Career interests</h3><div className="grid sm:grid-cols-2 gap-5"><Field label="LinkedIn URL (optional)"><input type="url" placeholder="https://www.linkedin.com/in/…" maxLength={500} className={inputClass} value={form.linkedin} onChange={e=>change('linkedin',e.target.value)}/></Field><Field label="Portfolio URL (optional)"><input type="url" placeholder="https://…" maxLength={500} className={inputClass} value={form.portfolio} onChange={e=>change('portfolio',e.target.value)}/></Field></div>
 <fieldset className="mt-5"><legend className="text-sm font-semibold mb-3">Opportunities you’re interested in (optional)</legend><div className="flex flex-wrap gap-x-6 gap-y-3">{INTERESTS.map(v=><label key={v} className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-[#16233F]" checked={form.interests.includes(v)} onChange={()=>multi('interests',v)}/>{v}</label>)}</div></fieldset>
 <div className="mt-5"><Field label="Preferred work locations (optional)"><input maxLength={500} className={inputClass} placeholder="Dallas–Fort Worth, remote, open to relocation…" value={form.locations} onChange={e=>change('locations',e.target.value)}/></Field></div></section>
 <section className="border-t border-navy/10 pt-7" aria-labelledby="resume-title"><h3 id="resume-title" className="font-serif text-xl mb-3">Your resume</h3><p className="text-sm text-navy/70 mb-4">PDF only, up to 3 MB. Save your profile first, then upload. Uploading or replacing a resume leaves partner sharing off until you opt in.</p>
 <div className="border border-dashed border-navy/30 bg-cream p-5" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(saved.exists&&!busy&&!dirty)upload(e.dataTransfer.files);}}>
 {saved.resume?<div className="mb-4"><p className="font-semibold text-sm">Resume uploaded · {Math.ceil(saved.resume.size/1024)} KB</p><a href="/api/profile/resume" className="underline text-sm" download>Download your saved resume</a></div>:<p className="text-sm mb-4">{saved.exists?'Choose a file or drop it here.':'Your upload will become available after your first profile save.'}</p>}
 <input ref={fileInput} type="file" accept="application/pdf,.pdf" className="hidden" aria-label="Resume PDF" onChange={e=>{upload(e.target.files);e.target.value='';}}/>
 <div className="flex flex-wrap gap-3"><button type="button" className={buttonClass} disabled={!saved.exists||dirty} onClick={()=>fileInput.current?.click()}>{saved.resume?'Replace PDF':'Upload PDF'}</button>{saved.resume&&<button type="button" className="border border-navy/20 rounded-sm px-4 py-3 text-xs font-bold whitespace-nowrap" disabled={dirty} onClick={()=>{if(window.confirm('Remove your saved resume and turn off future resume-book sharing?'))action('/api/profile/resume',{method:'DELETE'},'Resume removed and future sharing turned off.');}}>Remove resume</button>}</div></div>
 <label className="flex items-start gap-3 mt-5 text-sm leading-relaxed"><input className="mt-1 accent-[#16233F]" type="checkbox" checked={form.shareResume} disabled={!saved.resume} onChange={e=>change('shareResume',e.target.checked)}/><span>{CONSENT_TEXT}</span></label><p className="mt-2 text-xs text-navy/60">Use Save profile to apply a change to this checkbox.</p></section>
 <details className="border-t border-navy/10 pt-7"><summary className="font-serif text-xl cursor-pointer">Optional demographics</summary><p className="text-sm text-navy/70 my-4">These answers are for internal chapter records and aggregate reporting. They are excluded from individual recruiter profiles and resume books. You can skip any question, select “Prefer not to say,” or clear a previous answer and save.</p>
 <fieldset><legend className="text-sm font-semibold mb-3">Race / ethnicity — select all that apply</legend><div className="grid sm:grid-cols-2 gap-3">{ETHNICITIES.map(v=><label key={v} className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-[#16233F]" checked={form.ethnicity.includes(v)} onChange={()=>multi('ethnicity',v)}/>{v}</label>)}</div></fieldset>
 <div className="grid sm:grid-cols-2 gap-5 mt-6">{select('gender','Gender',GENDERS)}{select('lgbtq','Do you identify as LGBTQ+?',LGBTQ)}{select('international','International-student status',INTERNATIONAL)}</div></details>
 <div className="border-t border-navy/15 pt-6 flex flex-wrap items-center gap-4"><button type="submit" className={buttonClass}>{busy?'Saving…':'Save profile'}</button><span className="text-xs text-navy/60">Dues checkout is not enabled yet.</span></div>
 </fieldset>
 {error&&<p role="alert" className="mt-5 border border-red-300 bg-red-50 text-red-800 p-4 text-sm">{error}</p>}{notice&&<p role="status" className="mt-5 border border-navy/15 bg-cream p-4 text-sm">{notice}</p>}
 </form>;
}
