"use client";
import {useState,useEffect} from 'react';
export default function MemberDues(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);setError('');try{const res=await fetch('/api/dues',{cache:'no-store'}),body=await res.json();if(!res.ok)throw Error(body.error);setData(body);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{refresh();},[]);
 async function pay(plan){setBusy(true);setError('');try{const res=await fetch('/api/dues',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})}),body=await res.json();if(!res.ok)throw Error(body.error);window.location.assign(body.url);}catch(e){setError(e.message);setBusy(false);}}
 const button='px-5 py-3 rounded-sm text-sm font-bold bg-navy text-cream disabled:opacity-50';
 return <section className="mt-10 border border-navy/15 bg-white p-6 sm:p-8" aria-labelledby="dues-title"><p className="text-xs uppercase tracking-widest text-brass font-bold">Membership dues · Sandbox test</p><h2 id="dues-title" className="font-serif text-3xl mt-3">Your membership, connected.</h2><p className="mt-3 text-sm text-navy/70">Testing only. No real membership payment is collected here. Use a Stripe test card, never your real card.</p>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{!data&&!error&&<p className="mt-4">Checking dues…</p>}{data&&<div className="mt-6">{!data.profileExists?<p>Save your profile above, then refresh dues status to unlock checkout.</p>:data.paid?<div role="status"><p className="font-bold text-lg">Paid — {data.term} (test)</p><p>Covered through {data.coverageEnd}.</p></div>:!data.term?<p>Enrollment is currently closed.</p>:<><p className="mb-4">{data.term} · Dues not yet paid</p><div className="grid sm:grid-cols-2 gap-4"><div className="border border-navy/15 p-5"><h3 className="font-bold">Semester · $15</h3><p className="text-sm my-3">Coverage through {data.semesterEnd}. One-time payment.</p><button disabled={busy} className={button} onClick={()=>pay('semester')}>Test semester checkout</button></div>{data.annualAvailable&&<div className="border border-brass p-5"><h3 className="font-bold">Academic year · $25</h3><p className="text-sm my-3">Fall + spring through {data.annualEnd}. Save $5. Available through October 31.</p><button disabled={busy} className={button} onClick={()=>pay('annual')}>Test academic-year checkout</button></div>}</div></>}</div>}<button disabled={busy} onClick={refresh} className="mt-5 underline text-sm disabled:opacity-50">{busy?'Checking…':'Refresh dues status'}</button><p className="mt-3 text-xs text-navy/60">Already completed checkout? Refresh to verify your payment before trying again.</p></section>;
}
