"use client";
import {useEffect,useState} from 'react';
export default function OfferReports({review=false}){
 const [reports,setReports]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch(`/api/offers${review?'?review=1':''}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setReports(d.reports);};
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[review]);
 async function send(body,method){setBusy(true);setMessage('');try{const r=await fetch('/api/offers',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage(review?'Review saved. The public total reflects approved new offers.':'Offer reported. An officer will review it before it affects the chapter total.');return true;}catch(e){setMessage(e.message);return false;}finally{setBusy(false);}}
 return <section className="mt-12 border-t border-navy/20 pt-8" id="offer-reports"><p className="text-xs uppercase tracking-widest text-brass">MEMBER OUTCOMES</p><h2 className="font-serif text-3xl my-4">{review?'Review chapter offers.':'Your next step is worth celebrating.'}</h2><p className="text-sm mb-6">{review?'Confirm each report with the member. Only approve as new if it is not a duplicate or already included in the historical 72 offers. You cannot review your own report.':'Report an internship or full-time offer, whether or not you accepted it. Details stay private to you and chapter officers; only the reviewed total is public. Please submit each offer once.'}</p>
 {!review&&<form className="grid sm:grid-cols-2 gap-4" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await send(Object.fromEntries(new FormData(form)),'POST'))form.reset();}}><label>Company<input name="company" required maxLength={100} className="block border border-navy/20 bg-transparent w-full p-3 mt-2"/></label><label>Role<input name="role" required maxLength={150} className="block border border-navy/20 bg-transparent w-full p-3 mt-2"/></label><label>Offer type<select name="type" required className="block border border-navy/20 bg-transparent w-full p-3 mt-2"><option>Internship</option><option>Full-time</option></select></label><label>Date received<input type="date" name="date" required min="2023-01-01" max={new Date().toISOString().slice(0,10)} className="block border border-navy/20 bg-transparent w-full p-3 mt-2"/></label><button disabled={busy} className="bg-navy text-cream px-5 py-3 disabled:opacity-50 sm:col-span-2">{busy?'Saving…':'Report an offer'}</button></form>}
 <p role="status" className="my-4 text-sm">{message}</p><div className="space-y-3">{reports.map(r=><article key={r.id} className="border border-navy/15 p-4"><h3 className="font-semibold">{r.company} · {r.role}</h3><p className="text-sm mt-2">{review?`${r.name} · `:''}{r.type} · {r.date} · {r.status}{r.status==='approved'?(r.addToBaseline?' · Added to total':' · Already in historical total'):''}</p>{review&&<div className="flex flex-wrap gap-3 mt-4">{[['approved',true,'Approve as new'],['approved',false,'Already in historical 72'],['rejected',false,'Reject / duplicate'],['pending',false,'Return to review']].map(([status,addToBaseline,label])=><button className="border border-navy/30 px-3 py-2 text-xs disabled:opacity-50" disabled={busy} key={label} onClick={()=>send({id:r.id,status,addToBaseline},'PATCH')}>{label}</button>)}</div>}</article>)}</div></section>;
}
