"use client";
import {useEffect,useState} from 'react';
const button='bg-navy text-cream rounded-sm px-5 py-3 text-xs font-bold uppercase tracking-widest whitespace-nowrap disabled:opacity-50';
export default function ResumeBook(){const [members,setMembers]=useState([]),[selected,setSelected]=useState([]),[partner,setPartner]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/resume-book',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setMembers(d.members);setSelected([]);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function download(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/resume-book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,partner})});if(!r.ok){const d=await r.json();throw Error(d.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='ColorStack-UTA-resume-book.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice('Download prepared and release recorded. Review the files before sharing with the named company. Nothing was sent automatically.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const visible=members.filter(m=>[m.name,m.major,m.graduation,m.opportunity,m.careers,m.availability].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <form onSubmit={download} className="space-y-6"><p className="text-navy/70">Only members with both sharing consents and exactly one PDF appear here. Demographics and dues are excluded. Export up to 20 members per batch, with a combined PDF size under 3.5 MB.</p><button type="button" className={button} disabled={busy} onClick={load}>Refresh eligible members</button>
 <label className="block">Recipient company *<input required maxLength={150} value={partner} onChange={e=>setPartner(e.target.value)} className="block w-full border border-navy/20 bg-white p-3 mt-2" placeholder="Company receiving this release"/></label>
 <label className="block">Filter members<input type="search" value={query} onChange={e=>setQuery(e.target.value)} className="block w-full border border-navy/20 bg-white p-3 mt-2" placeholder="Name, major, opportunity, availability…"/></label>
 <fieldset disabled={busy} className="space-y-3"><legend className="mb-3 font-semibold">{members.length} eligible · {selected.length} selected</legend>{visible.map(m=><label key={m.id} className="flex gap-3 border border-navy/15 bg-white p-4"><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,m.id]:s.filter(id=>id!==m.id))}/><span><strong>{m.name}</strong><span className="block text-sm">{[m.major,m.graduation,m.opportunity,m.careers,m.availability].filter(Boolean).join(' · ')}</span></span></label>)}{!visible.length&&<p>No matching eligible resumes. Members must save a profile, upload one PDF, and opt in.</p>}</fieldset>
 <button className={button} disabled={busy||!selected.length||selected.length>20}>{busy?'Working…':'Download resume package'}</button><p className="text-sm text-navy/60">Includes a CSV index for Excel and individual PDFs. Release tracking records generation, not delivery. Downloaded copies cannot be revoked.</p>{error&&<p role="alert" className="text-red-800">{error}</p>}{notice&&<p role="status">{notice}</p>}</form>;
}
