import { EBOARD, OFFICERS } from "./content";
export const ABOUT_LINKS = [["/about", "Our story"], ["/about/leadership", "Leadership"], ["/about/archive", "Archive"], ["/about/traditions", "Traditions"], ["/about/national", "National"]];
// Each record snapshots a role for one semester. Shared photo paths avoid duplicate assets.
// Explicit rank bands leave space for new roles without depending on array position.
export const OFFICER_ORDER = { "Vice President": 200, "Advisor": 450, "Marketing Director": 530, "Career Programs Director": 540, "President": 100, "Co-President": 100, "Internal VP": 200, "External VP": 210, "Co-Vice President": 220, "Treasurer": 300, "Secretary": 400, "Recruitment Director": 500, "Corporate Outreach Director": 510, "Women of ColorStack Director": 520, "Socials & Graphics Director": 530 };
export const sortOfficers = records => [...records].sort((a,b) => a.displayOrder-b.displayOrder || a.name.localeCompare(b.name));
export const LEADERSHIP_RECORDS = [...EBOARD.map(person => ({ ...person, classification: "executive" })), ...OFFICERS.map(person => ({ ...person, classification: "director" }))].map((person, index) => ({
  ...person, id: `fall-2026-${index}`, semester: "Fall 2026", photoAlt: `Portrait of ${person.name}`, major: null, graduationYear: null, bio: null, linkedin: null, experience: null, companyLogo: null, displayOrder: OFFICER_ORDER[person.role] ?? 900,
}));
export const CURRENT_BOARD = { semester: "Fall 2026", executive: LEADERSHIP_RECORDS.filter(p => p.classification === "executive").sort((a,b) => a.displayOrder-b.displayOrder || a.name.localeCompare(b.name)), directors: LEADERSHIP_RECORDS.filter(p => p.classification === "director").sort((a,b) => a.displayOrder-b.displayOrder || a.name.localeCompare(b.name)) };
export const MILESTONES = [
  { year: "2024", semester: "Spring 2024", photo: "/images/archive/founding-spring-2024.jpg", photoCaption: "COLORSTACK UTA · SPRING 2024", photoAlt: "ColorStack UTA founding community gathered together in Spring 2024", title: "Chapter founded", body: "ColorStack UTA begins at The University of Texas at Arlington." },
  // Add additional milestones only when confirmed by chapter records.
  { year: "2026", semester: null, photo: null, photoCaption: null, photoAlt: null, title: "400+ community", body: "87+ reported internship & full-time offers. A growing community, opening doors together." },
];
export const PILLARS = [
  { name: "Community", title: "Find your people.", body: "Build relationships with students navigating the same classrooms, interviews, opportunities, and questions." },
  { name: "Development", title: "Build your craft.", body: "Technical workshops, career preparation, mentorship, and experiences designed to help students keep getting better." },
  { name: "Opportunity", title: "Take the next step.", body: "Industry connections, internships, conferences, programs, and opportunities that can change what’s possible." },
];
// Historical semesters are intentional archival shells; add only verified records and dated assets.
export const SEMESTERS = ["Spring 2026", "Fall 2025"].map(semester => ({ semester, slug: semester.toLowerCase().replace(" ", "-"), groupPhoto: null, officers: [], accomplishments: [], metrics: [], eventPhotos: [], milestones: [], traditions: [], reflection: null }));
const foundingOfficers = [{"name": "Juan Gamez", "role": "Co-Founder & Co-President", "semester": "Spring 2024", "displayOrder": 100, "linkedin": null}, {"name": "Ahmed Ibrahim", "role": "Co-Founder & Co-President", "semester": "Spring 2024", "displayOrder": 101, "linkedin": "https://www.linkedin.com/in/ahmed-ibrahim-se/"}, {"name": "Genesis Tapia Rodriguez", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 502, "linkedin": "https://www.linkedin.com/in/genesistr/"}, {"name": "Diana Rios", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 503, "linkedin": "https://www.linkedin.com/in/diana-rios25/"}, {"name": "Christian Soliman", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 504, "linkedin": "https://www.linkedin.com/in/christian-soliman-aba569238/"}, {"name": "Anthony Loza", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 505, "linkedin": "https://www.linkedin.com/in/anthonyloza02/"}, {"name": "Javier Cardoso", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 506, "linkedin": "https://www.linkedin.com/in/cardoso-javier/"}, {"name": "Jocelyn Vazquez", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 507, "linkedin": "https://www.linkedin.com/in/jocelyn-vazquez/"}, {"name": "Isaac Medrano", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 508, "linkedin": "https://www.linkedin.com/in/isaac-medrano-7746222a9/"}, {"name": "Cecilia Romero", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 509, "linkedin": null}, {"name": "Bethel Bezabeh", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 510, "linkedin": null}, {"name": "Kristen E.", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 511, "linkedin": "https://www.linkedin.com/in/kristen-e-811632220/"}, {"name": "Rodrigo Munoz", "role": "Founding Officer", "semester": "Spring 2024", "displayOrder": 512, "linkedin": "https://www.linkedin.com/in/rodrigomunozcs/"}];
SEMESTERS.push({ semester: "Spring 2024", slug: "spring-2024", groupPhoto: { src: "/images/archive/founding-spring-2024.jpg", alt: "ColorStack UTA founding community gathered together in Spring 2024", caption: "THE FOUNDING E-BOARD / SPRING 2024 · SHARED BY JUAN GAMEZ" }, source: { href: "https://lnkd.in/p/g37vGnZy", label: "Read Juan Gamez’s founding post ↗" }, officers: foundingOfficers, accomplishments: [], metrics: [], eventPhotos: [], milestones: [{ title: "Chapter founded", description: "ColorStack UTA begins at The University of Texas at Arlington in Spring 2024." }], traditions: [], reflection: "Founded by Co-Presidents Juan Gamez and Ahmed Ibrahim, ColorStack UTA began with a student-led commitment to community, academic support, and career opportunities for Black and Latinx students in tech." });
export const FOUNDING_CLASS = { year: 2024, officers: [], photos: [], story: null };
export const TRADITIONS = [{ number: "01", name: "Secured the Bag", tagline: "You got the offer. Now secure the bag.", nationalOrigin: "Spring 2022", origin: "Spring 2025", story: "Secured the Bag began as a ColorStack tradition celebrating members as they landed internships and full-time opportunities. ColorStack UTA brought the tradition to Arlington in Spring 2025, recognizing the work behind every offer and showing the next student what’s possible.", howItWorks: null,
  // Slides: { src, alt, memberName, company, role, semester, caption }. Preserve originals.
  photos: [{"src": "/images/traditions/manuel-arellano.jpg", "memberName": "Manuel Arellano", "company": "SEO Tech Developer", "role": "Software Engineering Intern", "semester": null, "alt": "Original Secured the Bag graphic celebrating Manuel Arellano, Software Engineering Intern at SEO Tech Developer", "caption": "SECURED THE BAG / COLORSTACK UTA"}, {"src": "/images/traditions/osbaldo-puente.jpg", "memberName": "Osbaldo Puente", "company": "Amazon", "role": "Software Development Engineer", "semester": null, "alt": "Original Secured the Bag graphic celebrating Osbaldo Puente, Software Development Engineer at Amazon", "caption": "SECURED THE BAG / COLORSTACK UTA"}, {"src": "/images/traditions/natalia-miranda.jpg", "memberName": "Natalia Miranda", "company": "GM Financial", "role": "Cybersecurity Intern", "semester": null, "alt": "Original Secured the Bag graphic celebrating Natalia Miranda, Cybersecurity Intern at GM Financial", "caption": "SECURED THE BAG / COLORSTACK UTA"}, {"src": "/images/traditions/nnanna-ejim.jpg", "memberName": "Nnanna Ejim", "company": "Amazon", "role": "Software Development Engineer Intern", "semester": null, "alt": "Original Secured the Bag graphic celebrating Nnanna Ejim, Software Development Engineer Intern at Amazon", "caption": "SECURED THE BAG / COLORSTACK UTA"}, {"src": "/images/traditions/juan-gamez.jpg", "memberName": "Juan Gamez", "company": "Microsoft", "role": "Software Engineer", "semester": null, "alt": "Original Secured the Bag graphic celebrating Juan Gamez, Software Engineer at Microsoft", "caption": "SECURED THE BAG / COLORSTACK UTA"}, {"src": "/images/traditions/jocelyn-vazquez.jpg", "memberName": "Jocelyn Vazquez", "company": "Fidelity Investments", "role": "Data Engineer Intern", "semester": null, "alt": "Original Secured the Bag graphic celebrating Jocelyn Vazquez, Data Engineer Intern at Fidelity Investments", "caption": "SECURED THE BAG / COLORSTACK UTA"}, {"src": "/images/traditions/christian-soliman.jpg", "memberName": "Christian Soliman", "company": "Atlassian", "role": "Software Engineer Intern", "semester": null, "alt": "Original Secured the Bag graphic celebrating Christian Soliman, Software Engineer Intern at Atlassian", "caption": "SECURED THE BAG / COLORSTACK UTA"}] }];
export function aboutMetadata(title, description, path) { return { title, description, alternates: { canonical: `https://colorstackuta.org${path}` } }; }
